# Semantic Kernel LLM Configuration

# Default model to use
default_model: "gpt-5"

# LLM Models Configuration
models:
  # OpenAI GPT-5
  gpt-5:
    provider: "openai"
    model_id: "gpt-5"
    api_key_env: "OPENAI_API_KEY"
    max_completion_tokens: 50000

# Routing Configuration
routing:
  # Rules for prompt routing based on keywords or patterns
  rules:
    - name: "WEATHER"
      keywords: ["weather", "pogoda", "temperatura", "temperature", "forecast", "prognoza", "rain", "deszcz", "snow", "śnieg", "sun", "słońce", "cloud", "chmura", "wind", "wiatr", "storm", "burza"]
      preferred_model: "gpt-5"
      system_prompt: "You are a weather information assistant. Provide accurate and helpful weather-related information."

    - name: "OTHER"
      keywords: []  # catches everything that doesn't match WEATHER
      preferred_model: "gpt-5"
      system_prompt: "Przepraszam, ale nie posiadam informacji na ten temat. To nie jest moja dziedzina specjalizacji. Mogę Ci pomóc tylko z informacjami związanymi z pogodą."

  # Default fallback model when no rules match
  fallback_model: "gpt-5"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/semantic-k.log"